image: "svinonek/debian-cpp"

stages:
  - build
  - tests

build:
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake  --build ./

tests:
  script:
    - python3 ../tests.py